package org.aitek.android.animalsgame.utils;

public enum Animal {

	BAT, BEAR, BISON, CAMEL, CAT, CHEETAH, CHIMPANZEE, COW, DEER, DOG, DOLPHIN, DONKEY, ELEPHANT, FROG, GIRAFFE, GORILLA, HIPPO, HORSE, HYENA, LION, ORANGUTAN, PANDA, ROOSTER, SQUIRREL, TIGER, WALRUS, WHALE, WOLF
}
